name: Bug report
description: Report a problem with ethotechnics.org
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the site. Include screenshots or console output if relevant.
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior.
      placeholder: "When I click..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click...
        3. Observe...
  - type: input
    id: url
    attributes:
      label: URL
      placeholder: "https://ethotechnics.org/..."
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Browser, device, and anything else helpful.
      placeholder: "Chrome 125 on macOS 14"
