/**
 * The public record of objections to the standards' clauses, as the weekly
 * presence-data workflow last rebuilt it from GitHub issues. The file is
 * generated by scripts/presence/objections-snapshot.ts; do not edit it by
 * hand. The rules it records are in src/utils/objections.ts.
 */
import data from "./generated/objections.json";
import type { ObjectionSnapshot } from "../utils/objections";

export const objectionRecord = data as ObjectionSnapshot;
