import type { AnchorLink, PageWithPermalink, PanelCopy } from "./types";

export type StandardEntry = {
  id: string;
  slug: string;
  title: string;
  description: string;
  status: string;
  version: string;
  effectiveDate: string;
  published: string;
};

export type DoctrineEntry = {
  id: string;
  title: string;
  description: string;
  href: string;
  eyebrow?: string;
  ctaLabel: string;
};

export type StandardsContent = PageWithPermalink & {
  anchorLinks: AnchorLink[];
  panelCopy: PanelCopy;
  standards: StandardEntry[];
  doctrine: DoctrineEntry[];
};

export type ClauseRequirementLevel = "MUST" | "SHOULD";
export type ClauseType = "right" | "obligation";

export type StandardClause = {
  id: string;
  standardId: string;
  displayId: string;
  type: ClauseType;
  requirementLevel: ClauseRequirementLevel;
  condition: string;
  obligation: string;
  evidenceRequired: string[];
  timeBound: string;
  failureModes?: string[];
  relatedMechanisms: string[];
  relatedValidators: string[];
};

export const standardsContent: StandardsContent = {
  pageTitle: "Standards — Ethotechnics Institute",
  pageDescription:
    "Canonical standards and doctrine stewarded by the Institute of Ethotechnics.",
  permalink: "/standards",
  anchorLinks: [
    { href: "#active", label: "Active standards" },
    { href: "#doctrine", label: "Doctrine" },
  ],
  panelCopy: {
    eyebrow: "Stewardship",
    title: "Documented for citation",
    description:
      "Each standard ships with stable IDs, publication metadata, and direct references to mechanisms.",
  },
  standards: [
    {
      id: "STD-01",
      slug: "std-01-temporal-rights",
      title: "The Temporal Bill of Rights",
      description:
        "Defines the seven inalienable rights protecting human time against automated systems.",
      status: "Draft for Ratification",
      version: "1.0",
      effectiveDate: "January 2026",
      published: "2026-01-01",
    },
    {
      id: "STD-02",
      slug: "std-02-contestability-recourse",
      title: "The Contestability & Recourse Standard",
      description:
        "Defines contestability, review, and remedy obligations for consequential systems.",
      status: "Draft for Peer Review",
      version: "0.9",
      effectiveDate: "TBD (proposed 2026)",
      published: "2026-01-01",
    },
  ],
  doctrine: [
    {
      id: "core-axioms",
      title: "Core axioms",
      description:
        "First principles for accountable system design and governance.",
      href: "/standards/core-axioms",
      eyebrow: "Doctrine",
      ctaLabel: "View axioms",
    },
    {
      id: "ethotechnics-for-agents",
      title: "Ethotechnics for Agents",
      description:
        "Mechanism-first practice for implementing STD-01 and STD-02 in real agent systems.",
      href: "/standards/ethotechnics-for-agents",
      eyebrow: "Practice",
      ctaLabel: "View practice",
    },
    {
      id: "std-01-mapping-artifact",
      title: "STD-01 mapping artifact",
      description: "Brandless end-to-end mapping from harm to binding change.",
      href: "/standards/std-01-mapping-artifact",
      eyebrow: "STD-01 reference",
      ctaLabel: "Open mapping",
    },
    {
      id: "std-01-rights-matrix",
      title: "STD-01 rights matrix",
      description:
        "Crosswalk linking STD-01 rights to validators and mechanisms.",
      href: "/standards/std-01-rights-matrix",
      eyebrow: "STD-01 reference",
      ctaLabel: "View matrix",
    },
    {
      id: "micro-diagram-language",
      title: "Micro-diagram language",
      description: "Canonical diagram shapes, line styles, and axes.",
      href: "/standards/micro-diagram-language",
      eyebrow: "Reference",
      ctaLabel: "View diagram spec",
    },
    {
      id: "std-01-minimum-binding-set",
      title: "STD-01 minimum binding set",
      description:
        "Minimum binding requirements per right with clause references.",
      href: "/standards/std-01-minimum-binding-set",
      eyebrow: "STD-01 reference",
      ctaLabel: "Review binding set",
    },
    {
      id: "where-this-binds",
      title: "Where this binds",
      description:
        "Guidance for referencing standards in contracts, procurement, and audits.",
      href: "/standards/where-this-binds",
      eyebrow: "Governance",
      ctaLabel: "See guidance",
    },
    {
      id: "glossary",
      title: "Glossary",
      description: "Immutable terminology and canonical definitions.",
      href: "/glossary",
      eyebrow: "Reference",
      ctaLabel: "Browse glossary",
    },
  ],
};

export const standardClauses: Record<string, StandardClause[]> = {
  "STD-01": [
    {
      id: "STD-01.1.1",
      standardId: "STD-01",
      displayId: "§1.1",
      type: "right",
      requirementLevel: "MUST",
      condition: "active automated process is in progress",
      obligation: "provide a visible, universally accessible halt control",
      evidenceRequired: ["ui_control", "event_log"],
      timeBound: "immediate",
      relatedMechanisms: ["MEC-05"],
      relatedValidators: ["VAL-01"],
    },
    {
      id: "STD-01.1.2",
      standardId: "STD-01",
      displayId: "§1.2",
      type: "right",
      requirementLevel: "MUST",
      condition: "a process is halted by the user",
      obligation: "preserve the paused state for return without penalty",
      evidenceRequired: ["state_snapshot", "retention_policy"],
      timeBound: "reasonable duration",
      relatedMechanisms: ["MEC-02"],
      relatedValidators: ["VAL-01"],
    },
    {
      id: "STD-01.1.3",
      standardId: "STD-01",
      displayId: "§1.3",
      type: "right",
      requirementLevel: "MUST",
      condition: "user is in a multi-step flow",
      obligation: "offer a permanent exit option on every screen",
      evidenceRequired: ["ui_state", "interaction_map"],
      timeBound: "continuous",
      relatedMechanisms: ["MEC-02"],
      relatedValidators: ["VAL-02"],
    },
    {
      id: "STD-01.2.1",
      standardId: "STD-01",
      displayId: "§2.1",
      type: "right",
      requirementLevel: "MUST",
      condition: "user seeks to end a relationship with a system",
      obligation: "allow exit with equal or less friction than entry",
      evidenceRequired: ["journey_map", "time_cost_log"],
      timeBound: "on demand",
      relatedMechanisms: ["MEC-02"],
      relatedValidators: ["VAL-01"],
    },
    {
      id: "STD-01.2.2",
      standardId: "STD-01",
      displayId: "§2.2",
      type: "right",
      requirementLevel: "MUST",
      condition: "entry required a single step",
      obligation: "exit requires no more than one step",
      evidenceRequired: ["journey_map", "ui_state"],
      timeBound: "on demand",
      relatedMechanisms: ["MEC-02"],
      relatedValidators: ["VAL-02"],
    },
    {
      id: "STD-01.2.3",
      standardId: "STD-01",
      displayId: "§2.3",
      type: "right",
      requirementLevel: "MUST",
      condition: "user initiates resignation or cancellation",
      obligation: "avoid mandatory retention scripts before exit",
      evidenceRequired: ["journey_map", "policy"],
      timeBound: "on demand",
      relatedMechanisms: ["MEC-02"],
      relatedValidators: ["VAL-02"],
    },
    {
      id: "STD-01.3.1",
      standardId: "STD-01",
      displayId: "§3.1",
      type: "right",
      requirementLevel: "MUST",
      condition: "process includes pending, processing, or review states",
      obligation: "set hard clocks for each state",
      evidenceRequired: ["system_sla", "event_log"],
      timeBound: "state-specific",
      relatedMechanisms: ["MEC-04"],
      relatedValidators: ["VAL-03"],
    },
    {
      id: "STD-01.3.2",
      standardId: "STD-01",
      displayId: "§3.2",
      type: "right",
      requirementLevel: "MUST",
      condition: "timeout threshold is reached",
      obligation: "provide a failure response or human escalation",
      evidenceRequired: ["escalation_policy", "event_log"],
      timeBound: "at timeout",
      relatedMechanisms: ["MEC-04", "MEC-06"],
      relatedValidators: ["VAL-03"],
    },
    {
      id: "STD-01.3.3",
      standardId: "STD-01",
      displayId: "§3.3",
      type: "right",
      requirementLevel: "MUST",
      condition: "user is asked to commit to a process",
      obligation: "declare expected duration before commitment",
      evidenceRequired: ["ui_copy", "journey_map"],
      timeBound: "pre-commitment",
      relatedMechanisms: ["MEC-04"],
      relatedValidators: ["VAL-03"],
    },
    {
      id: "STD-01.4.1",
      standardId: "STD-01",
      displayId: "§4.1",
      type: "right",
      requirementLevel: "MUST",
      condition: "user performs a consequential action",
      obligation: "provide an undo window for reversals",
      evidenceRequired: ["ui_state", "policy"],
      timeBound: "defined window",
      relatedMechanisms: ["MEC-02"],
      relatedValidators: ["VAL-01"],
    },
    {
      id: "STD-01.4.2",
      standardId: "STD-01",
      displayId: "§4.2",
      type: "right",
      requirementLevel: "MUST",
      condition: "system deletes or removes content",
      obligation: "use non-destructive defaults with soft-delete",
      evidenceRequired: ["data_retention_policy", "event_log"],
      timeBound: "default behavior",
      relatedMechanisms: ["MEC-02"],
      relatedValidators: ["VAL-01"],
    },
    {
      id: "STD-01.5.1",
      standardId: "STD-01",
      displayId: "§5.1",
      type: "right",
      requirementLevel: "MUST",
      condition: "user is waiting in a queue or hold state",
      obligation: "show queue position and expected wait time",
      evidenceRequired: ["ui_state", "queue_metrics"],
      timeBound: "continuous",
      relatedMechanisms: ["MEC-04"],
      relatedValidators: ["VAL-02"],
    },
    {
      id: "STD-01.5.2",
      standardId: "STD-01",
      displayId: "§5.2",
      type: "right",
      requirementLevel: "MUST",
      condition: "system reports progress or waiting status",
      obligation: "avoid fake progress indicators or placebo signals",
      evidenceRequired: ["ui_state", "event_log"],
      timeBound: "continuous",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: ["VAL-02"],
    },
    {
      id: "STD-01.5.3",
      standardId: "STD-01",
      displayId: "§5.3",
      type: "right",
      requirementLevel: "MUST",
      condition: "wait time exceeds five minutes",
      obligation: "offer asynchronous options",
      evidenceRequired: ["ui_state", "journey_map"],
      timeBound: "five minutes",
      relatedMechanisms: ["MEC-04"],
      relatedValidators: ["VAL-02"],
    },
    {
      id: "STD-01.6.1",
      standardId: "STD-01",
      displayId: "§6.1",
      type: "right",
      requirementLevel: "MUST",
      condition: "automated denial or escalation request occurs",
      obligation: "provide a defined escalation path to a human",
      evidenceRequired: ["policy", "support_workflow"],
      timeBound: "on request",
      relatedMechanisms: ["MEC-06"],
      relatedValidators: ["VAL-02"],
    },
    {
      id: "STD-01.6.2",
      standardId: "STD-01",
      displayId: "§6.2",
      type: "right",
      requirementLevel: "MUST",
      condition: "automation impacts a user outcome",
      obligation: "operating institution accepts liability",
      evidenceRequired: ["policy", "governance_record"],
      timeBound: "ongoing",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: ["VAL-02"],
    },
    {
      id: "STD-01.7.1",
      standardId: "STD-01",
      displayId: "§7.1",
      type: "right",
      requirementLevel: "MUST",
      condition: "system imposes compliance or usage burden",
      obligation: "measure and publish the time tax",
      evidenceRequired: ["burden_report", "time_cost_log"],
      timeBound: "scheduled reporting",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: ["VAL-01"],
    },
    {
      id: "STD-01.7.2",
      standardId: "STD-01",
      displayId: "§7.2",
      type: "right",
      requirementLevel: "MUST",
      condition: "governance metrics are tracked",
      obligation: "include burden as a reportable metric",
      evidenceRequired: ["governance_dashboard"],
      timeBound: "ongoing",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: ["VAL-01"],
    },
  ],
  "STD-02": [
    {
      id: "STD-02.1.1",
      standardId: "STD-02",
      displayId: "§1.1",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "automation materially affects a person",
      obligation: "disclose that automated decisioning occurred",
      evidenceRequired: ["ui_notice", "policy"],
      timeBound: "at impact",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: [],
    },
    {
      id: "STD-02.1.2",
      standardId: "STD-02",
      displayId: "§1.2",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "automation changes status, access, or resources",
      obligation: "state what changed and why it matters",
      evidenceRequired: ["ui_notice", "decision_log"],
      timeBound: "at impact",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: [],
    },
    {
      id: "STD-02.1.3",
      standardId: "STD-02",
      displayId: "§1.3",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "person receives an adverse or consequential outcome",
      obligation: "provide a review/appeal path with timelines",
      evidenceRequired: ["appeal_policy", "ui_copy"],
      timeBound: "immediate",
      relatedMechanisms: ["MEC-06"],
      relatedValidators: [],
    },
    {
      id: "STD-02.2.1",
      standardId: "STD-02",
      displayId: "§2.1",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "system takes an action or decision",
      obligation: "maintain a record of tool calls and state changes",
      evidenceRequired: ["action_log", "audit_trail"],
      timeBound: "continuous",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: [],
    },
    {
      id: "STD-02.2.2",
      standardId: "STD-02",
      displayId: "§2.2",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "receipt is generated for an action",
      obligation: "include reason codes and key inputs (redacted as needed)",
      evidenceRequired: ["receipt_template", "policy"],
      timeBound: "at action",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: [],
    },
    {
      id: "STD-02.2.3",
      standardId: "STD-02",
      displayId: "§2.3",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "receipt is issued",
      obligation: "identify accountable operator and contact channel",
      evidenceRequired: ["receipt_template", "contact_directory"],
      timeBound: "at action",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: [],
    },
    {
      id: "STD-02.3.1",
      standardId: "STD-02",
      displayId: "§3.1",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "person is materially affected",
      obligation: "grant standing regardless of status or credentials",
      evidenceRequired: ["policy", "appeal_workflow"],
      timeBound: "on request",
      relatedMechanisms: ["MEC-06"],
      relatedValidators: [],
    },
    {
      id: "STD-02.3.2",
      standardId: "STD-02",
      displayId: "§3.2",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "a contestation is filed",
      obligation: "avoid retaliation or punitive impacts",
      evidenceRequired: ["policy", "case_log"],
      timeBound: "ongoing",
      relatedMechanisms: ["MEC-06"],
      relatedValidators: [],
    },
    {
      id: "STD-02.3.3",
      standardId: "STD-02",
      displayId: "§3.3",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "decision is delivered via a channel",
      obligation: "offer contestation in the same channel",
      evidenceRequired: ["ui_state", "journey_map"],
      timeBound: "immediate",
      relatedMechanisms: ["MEC-06"],
      relatedValidators: [],
    },
    {
      id: "STD-02.4.1",
      standardId: "STD-02",
      displayId: "§4.1",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "appeals are accepted",
      obligation: "publish timelines for acknowledgment, review, resolution",
      evidenceRequired: ["sla_doc", "ui_copy"],
      timeBound: "published",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: [],
    },
    {
      id: "STD-02.4.2",
      standardId: "STD-02",
      displayId: "§4.2",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "review concerns high-stakes domains",
      obligation: "provide transparent status updates and expected resolution",
      evidenceRequired: ["status_updates", "queue_metrics"],
      timeBound: "continuous",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: [],
    },
    {
      id: "STD-02.4.3",
      standardId: "STD-02",
      displayId: "§4.3",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "review deadlines are missed",
      obligation: "escalate to higher-authority or trigger failsafe remedy",
      evidenceRequired: ["escalation_policy", "event_log"],
      timeBound: "at deadline breach",
      relatedMechanisms: ["MEC-06"],
      relatedValidators: [],
    },
    {
      id: "STD-02.5.1",
      standardId: "STD-02",
      displayId: "§5.1",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "harm is reversible",
      obligation: "support undo/rollback without extraordinary effort",
      evidenceRequired: ["remedy_policy", "ui_state"],
      timeBound: "on request",
      relatedMechanisms: ["MEC-06"],
      relatedValidators: [],
    },
    {
      id: "STD-02.5.2",
      standardId: "STD-02",
      displayId: "§5.2",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "harm is irreversible",
      obligation: "provide a defined compensation pathway",
      evidenceRequired: ["remedy_policy", "case_log"],
      timeBound: "on request",
      relatedMechanisms: ["MEC-06"],
      relatedValidators: [],
    },
    {
      id: "STD-02.5.3",
      standardId: "STD-02",
      displayId: "§5.3",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "remedy is issued",
      obligation: "assign authority to named humans",
      evidenceRequired: ["org_chart", "authority_matrix"],
      timeBound: "ongoing",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: [],
    },
    {
      id: "STD-02.6.1",
      standardId: "STD-02",
      displayId: "§6.1",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "automated denial or action occurs",
      obligation: "offer human review on request",
      evidenceRequired: ["review_policy", "support_workflow"],
      timeBound: "on request",
      relatedMechanisms: ["MEC-06"],
      relatedValidators: [],
    },
    {
      id: "STD-02.6.2",
      standardId: "STD-02",
      displayId: "§6.2",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "reviewers are evaluated",
      obligation: "avoid incentives that bias against remedies",
      evidenceRequired: ["performance_policy", "incentive_plan"],
      timeBound: "ongoing",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: [],
    },
    {
      id: "STD-02.6.3",
      standardId: "STD-02",
      displayId: "§6.3",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "logs support review or redress",
      obligation: "retain tamper-evident records long enough for investigation",
      evidenceRequired: ["audit_trail", "retention_policy"],
      timeBound: "retention term",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: [],
    },
    {
      id: "STD-02.7.1",
      standardId: "STD-02",
      displayId: "§7.1",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "automation causes errors or latency",
      obligation: "operator accepts liability for harms",
      evidenceRequired: ["policy", "governance_record"],
      timeBound: "ongoing",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: [],
    },
    {
      id: "STD-02.7.2",
      standardId: "STD-02",
      displayId: "§7.2",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "vendors manage logs or controls",
      obligation: "operators still guarantee access and remedy",
      evidenceRequired: ["vendor_contract", "access_policy"],
      timeBound: "ongoing",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: [],
    },
    {
      id: "STD-02.7.3",
      standardId: "STD-02",
      displayId: "§7.3",
      type: "obligation",
      requirementLevel: "MUST",
      condition: "automation throughput increases",
      obligation: "fund review capacity proportional to actions",
      evidenceRequired: ["capacity_plan", "case_volume_metrics"],
      timeBound: "ongoing",
      relatedMechanisms: ["MEC-01"],
      relatedValidators: [],
    },
  ],
};
