/**
 * The GitHub Action in action.yml runs the record conformance checker from
 * this repository's own checkout, with the Node every hosted runner already
 * has, so it works without the npm package being published. That needs one
 * file with its one dependency (zod) bundled in. This script writes it to
 * packages/conformance/action/cli.mjs; with --check it fails when the
 * committed file no longer matches the source, the way content:check guards
 * the generated content files.
 *
 * Bun is pinned in package.json (packageManager), and the same Bun produces
 * the same bundle, so the check does not drift between machines.
 */
import { readFile, writeFile } from "node:fs/promises";

const ENTRY = "packages/conformance/src/cli.ts";
const OUT = "packages/conformance/action/cli.mjs";
const NOTICE =
  "// Generated by `bun run conformance:action` from packages/conformance/src. Do not edit.";

const result = await Bun.build({
  entrypoints: [ENTRY],
  target: "node",
  format: "esm",
  minify: true,
  sourcemap: "none",
});

if (!result.success || !result.outputs[0]) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

const bundled = await result.outputs[0].text();
// The shebang has to stay the first line; the notice goes under it.
const [first, ...rest] = bundled.split("\n");
const expected = first?.startsWith("#!")
  ? [first, NOTICE, ...rest].join("\n")
  : [NOTICE, bundled].join("\n");

if (process.argv.includes("--check")) {
  const committed = await readFile(OUT, "utf8").catch(() => "");
  if (committed !== expected) {
    console.error(
      `${OUT} is out of date with ${ENTRY} and the code it imports. Run: bun run conformance:action`,
    );
    process.exit(1);
  }
  console.log(`✅ Up to date: ${OUT}`);
} else {
  await writeFile(OUT, expected, "utf8");
  console.log(`✨ Generated: ${OUT}`);
}
